### ISSUE TITLE
Not able to setup passport authentication

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/docs-3.0.1#8]
Followed instructions to setup passport authentication using facebook using this document
https://gluu.org/docs/ce/3.0.1/authn-guide/passport/#setup-passportjs-with-gluu ( through step 11), but Gluu is not redirecting to facebook login page.
getting error "Go back and register!"

oxauth logs

2017-04-18 02:54:22,740 ERROR [qtp242131142-19] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:415) - Failed to get attributes from session
2017-04-18 02:54:50,707 INFO  [qtp242131142-10] [org.xdi.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:369) - JWT authentication failed: Cannot verify the JWT
org.xdi.oxauth.model.exception.InvalidJwtException: Cannot verify the JWT
        at org.xdi.oxauth.model.token.ClientAssertion.<init>(ClientAssertion.java:49) ~[classes/:?]
        at org.xdi.oxauth.auth.AuthenticationFilter.processJwtAuth(AuthenticationFilter.java:345) [classes/:?]
        at org.xdi.oxauth.auth.AuthenticationFilter.access$200(AuthenticationFilter.java:67) [classes/:?]
        at org.xdi.oxauth.auth.AuthenticationFilter$1.process(AuthenticationFilter.java:113) [classes/:?]
        at org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.xdi.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:89) [classes/:?]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]

Similar issue reported by user - https://support.gluu.org/authentication/3932/passport-trouble/

Can you please check if instructions provided are correct/complete

**Comment by arvindsinghtomar** [comment]
@sahiliamsso Did you restarted gluu server or passport service after configuring passport for facebook?

**Comment by sahiliamsso** [comment]
Yes i did @arvindsinghtomar

**Comment by arvindsinghtomar** [comment]
Can you provide passport logs?

**Comment by sahiliamsso** [comment]
017-04-18 21:45:51,641 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Extension module key not found
2017-04-18 21:45:51,641 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Permission dynamic scope. Destroy
2017-04-18 21:45:51,642 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Permission dynamic scope. Destroyed successfully
2017-04-18 21:45:51,657 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Permission dynamic scope. Initialization
2017-04-18 21:45:51,657 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Permission dynamic scope. Initialized successfully
2017-04-18 21:45:51,682 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - UMA authorization policy. Initialization
2017-04-18 21:45:51,683 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - UMA authorization policy. Initialization. Count authorized clients: 2
2017-04-18 21:45:51,683 INFO  [pool-2-thread-8] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - UMA authorization policy. Initialized successfully
2017-04-18 21:48:13,628 INFO  [qtp242131142-10] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Basic. Prepare for Step 1 method call
2017-04-18 21:48:18,161 INFO  [qtp242131142-16] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Basic. Prepare for Step 1 method call
2017-04-18 21:48:23,040 INFO  [qtp242131142-15] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Basic. Prepare for Step 1 method call
2017-04-18 21:48:24,577 INFO  [qtp242131142-11] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Basic. Prepare for Step 1 method call
2017-04-18 21:48:25,435 INFO  [qtp242131142-12] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:219) - Passport: Basic. Prepare for Step 1 method call

**Comment by willow9886** [comment]
Hi @arvindsinghtomar were you able to replicate and resolve this issue?

**Comment by sahiliamsso** [comment]
re-installed gluu server and its working fine. No issues with passport component
